import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ux/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-blue-200 min-h-screen">
        <Navbar />
        <main>{children}</main>
        {/* <footer /> TBD */}
      </body>
    </html>
  );
}
