import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./providers/query-provider";
import { SkillsProvider } from "./providers/skills-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-citrus-snow">
        <QueryProvider>
          <SkillsProvider>{children}</SkillsProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
