import {
  RiAmazonFill,
  RiQuestionMark,
  RemixiconComponentType,
  RiGoogleFill,
  RiReactjsFill,
  RiNextjsFill,
  RiNodejsFill,
  RiCodeSSlashFill,
  RiJavascriptFill,
  RiShieldCheckFill,
  RiHtml5Fill,
  RiBootstrapFill,
  RiWindyFill,
  RiRouteFill,
  RiFlashlightFill,
  RiCodeBoxFill,
  RiDatabase2Fill,
  RiDatabaseFill,
  RiLinksFill,
  RiTestTubeFill,
  RiTeamFill,
  RiLoopLeftFill,
  RiGithubFill,
  RiGitBranchFill,
  RiSendPlaneFill,
  RiFlowChart,
  RiNotification3Fill,
  RiLineChartFill,
  RiCloudFill,
  RiFunctionFill,
} from "@remixicon/react";

export const SILLY_QUOTES = [
  "Nothing is as permanent as a temporary solution that works.",
  "Give a man a program, and he'll be frustrated for a day. Teach a man to program, and he'll be frustrated for a lifetime.",
  "Debugging is like being the detective in a crime movie where you're also the murderer.",
  "In order to understand recursion, one must first understand recursion.",
  "Can learn to exit Vim, if needed",
  "One of the main causes of the fall of the Roman Empire was that, lacking zero, they had no way to indicate successful termination of their C programs.",
];

export const ICONS: Record<string, RemixiconComponentType> = {
  RiAmazonFill,
  RiGoogleFill,
  RiQuestionMark,
  RiReactjsFill,
  RiNextjsFill,
  RiNodejsFill,
  RiCodeSSlashFill,
  RiJavascriptFill,
  RiShieldCheckFill,
  RiHtml5Fill,
  RiBootstrapFill,
  RiWindyFill,
  RiRouteFill,
  RiFlashlightFill,
  RiCodeBoxFill,
  RiDatabase2Fill,
  RiDatabaseFill,
  RiLinksFill,
  RiTestTubeFill,
  RiTeamFill,
  RiLoopLeftFill,
  RiGithubFill,
  RiGitBranchFill,
  RiSendPlaneFill,
  RiFlowChart,
  RiNotification3Fill,
  RiLineChartFill,
  RiCloudFill,
  RiFunctionFill,
};

export const EMAIL_MESSAGE_MAX_LENGTH = 2000;
